version: '5.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

#  first analysis:
    #run: r:v2 analysis/first_analysis.R
    #needs: [generate-dataset]
    #outputs:
      #highly_sensitive:
        #cohort: output/first_analysis.feather